#!/usr/bin/with-contenv /bin/sh

sed -i "s@%CAKEBOX_USER%@${CAKEBOX_USER:-"nobody"}@g" /usr/share/cakebox/config/default.php
sed -i "s@%CAKEBOX_GROUP%@${CAKEBOX_GROUP:-"nogroup"}@g" /usr/share/cakebox/config/default.php
sed -i "s@%CAKEBOX_ROOT%@${CAKEBOX_ROOT:-"/usr/share/cakebox/"}@g" /usr/share/cakebox/config/default.php
sed -i "s@%CAKEBOX_ACCESS%@${CAKEBOX_ACCESS:-"/access/"}@g" /usr/share/cakebox/config/default.php
sed -i "s@%CAKEBOX_LANGUAGE%@${CAKEBOX_LANGUAGE:-"en"}@g" /usr/share/cakebox/config/default.php
sed -i "s@%DIRECTORY_IGNORE_DOTFILES%@${DIRECTORY_IGNORE_DOTFILES:-"TRUE"}@g" /usr/share/cakebox/config/default.php
sed -i "s@%DIRECTORY_IGNORE%@${DIRECTORY_IGNORE:-"//"}@g" /usr/share/cakebox/config/default.php
sed -i "s@%PLAYER_DEFAULT_TYPE%@${PLAYER_DEFAULT_TYPE:-"html5"}@g" /usr/share/cakebox/config/default.php
sed -i "s@%PLAYER_AUTO_PLAY%@${PLAYER_AUTO_PLAY:-"FALSE"}@g" /usr/share/cakebox/config/default.php
sed -i "s@%RIGHTS_CAN_PLAY_MEDIA%@${RIGHTS_CAN_PLAY_MEDIA:-"TRUE"}@g" /usr/share/cakebox/config/default.php
sed -i "s@%RIGHTS_CAN_DOWNLOAD_FILE%@${RIGHTS_CAN_DOWNLOAD_FILE:-"TRUE"}@g" /usr/share/cakebox/config/default.php
sed -i "s@%RIGHTS_CAN_ARCHIVE_DIRECTORY%@${RIGHTS_CAN_ARCHIVE_DIRECTORY:-"FALSE"}@g" /usr/share/cakebox/config/default.php
sed -i "s@%RIGHTS_CAN_DELETE%@${RIGHTS_CAN_DELETE:-"FALSE"}@g" /usr/share/cakebox/config/default.php
sed -i "s@%BS_LOGIN%@${BS_LOGIN:-""}@g" /usr/share/cakebox/config/default.php
sed -i "s@%BS_PASSWORD%@${BS_PASSWORD:-""}@g" /usr/share/cakebox/config/default.php
sed -i "s@%BS_API_KEY%@${BS_API_KEY:-""}@g" /usr/share/cakebox/config/default.php
